In [1]:
import numpy as np
import pandas as pd

In [12]:
FILE_PATH = 'banknote_net.feather'
df = pd.read_feather(FILE_PATH)
df

,v_0,v_1,v_2,v_3,v_4,v_5,v_6,v_7,v_8,v_9,...,v_248,v_249,v_250,v_251,v_252,v_253,v_254,v_255,Currency,Denomination
0,0.423395,0.327657,2.568988,3.166228,4.801421,5.531792,2.458083,1.218453,0.000000,1.116785,...,0.000000,2.273451,5.790633,0.000000,0.000000,0.000000,5.635400,0.000000,AUD,100_1
1,1.158823,1.669602,3.638447,2.823524,4.839890,2.777757,0.753350,0.764005,0.347871,1.928572,...,0.000000,2.329623,3.516146,0.000000,0.000000,0.000000,2.548191,1.053410,AUD,100_1
2,0.000000,0.958235,4.706119,1.688242,3.312702,4.516483,0.000000,1.876461,2.250795,1.883192,...,0.811282,5.591417,1.879267,0.641139,0.571079,0.000000,1.861483,2.172145,AUD,100_1
3,0.920511,1.820294,3.939334,3.206829,6.253655,0.942557,2.952453,0.000000,2.064298,1.367196,...,1.764936,3.415151,2.518404,0.582229,1.105192,0.000000,1.566918,0.533945,AUD,100_1
4,0.331918,0.000000,3.330771,3.023437,4.369099,5.177336,1.499362,0.590646,0.553625,1.405708,...,0.000000,4.615945,4.825463,0.302261,0.378229,0.000000,2.710654,0.325945,AUD,100_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24821,0.000000,3.076672,1.849998,0.635259,6.472688,0.000000,2.214436,0.000000,2.988177,3.404484,...,4.631783,2.729344,0.000000,1.506066,0.000000,1.067279,3.900349,0.004177,USD,5_2
24822,0.000000,4.471694,2.024621,0.194067,6.469818,0.000000,1.756854,0.000000,3.129118,4.005479,...,4.721860,2.495226,0.000000,2.055333,0.000000,1.332700,4.545783,0.030185,USD,5_2
24823,0.000000,3.726544,1.780134,1.752426,3.299378,0.422422,0.527200,0.504323,2.486856,0.927679,...,3.888309,1.271812,0.000000,0.000000,0.676830,0.510450,2.906571,0.363790,USD,5_2
24824,0.250622,2.615436,1.329533,0.741571,5.485542,0.000000,2.267793,0.000000,2.881907,2.511872,...,4.994749,0.000000,0.000000,2.440658,0.000000,0.737470,4.139810,0.314729,USD,5_2
24825,0.000000,4.508471,1.943896,0.000000,5.995752,0.000000,4.632102,0.000000,3.998712,4.283959,...,6.761415,0.000000,1.121088,1.330410,0.000000,0.497376,4.628631,0.000000,USD,5_2

56